### PR TITLE
Changed metered healthchecks from counters to gauges

### PR DESCRIPTION
**Pull request by martinroddam**

### CODE REVIEW

**Comment by JamieAP** [comment]
Why?

**Comment by JamieAP** [comment]
In fact, I'm not sure why this instrumentation exists at all. What is the use case?

**Comment by jakekeeys** [comment]
@martinroddam this counter represents the count of invocations why are we changing this behaviour?... The current state its already exposed from the health endpoint and really k8s should be the only thing concerned with with... don't see what value we gain from also surfacing this in metrics

**Comment by jakekeeys** [comment]
your dependencies should be individually monitored for health outside of the usages

**Comment by martinroddam** [comment]
I want to see when was the app healthy, or not. The health endpoint is hit at a constant rate and so time series data doesn't help either.

This addition by Vaishakh allows users to see a possible root cause of errors on a Grafana dashboard alongside the error rate. It also allows alerting off healthcheck failures using our highly available metrics/alerting mechanism. Health check data is largely ignored right now.

**Comment by martinroddam** [comment]
k8s doesn't actually do anything if your app's checks are failing. It only does anything if the health check cannot be performed at all and returns a non-200 status code.

**Comment by jakekeeys** [comment]
the op lib should return a non 200 code when a check returns unhealthy

**Comment by JamieAP** [comment]
The fix to that sounds like having the health endpoint return a non-200 on failed checks. Not this instrumentation.

Nobody should be building alerts using these metrics. They should be using metrics based on actual app performance. Health checks are in most cases loose approximations of actual application behaviour (i.e. making test calls to endpoint on some third party API instead of _real_ calls). 

A majority of the things instrumented for errors would not show failing health checks at the same time.
 
As an example, an SFTP poller might have a health check that asserts it can open a connection to a server. While the instrumentation might register errors if some files on that server can't be opened due to perms.

This introduces a lazy approach to app monitoring that we shouldn't encourage (this instrumentation in general, rather than the PR).

**Comment by jakekeeys** [comment]
https://health.dev.uw.systems/?ns=telecom

**Comment by povilasv** [comment]
I think op libs does return non 200 -> https://github.com/utilitywarehouse/go-operational/blob/master/op/handlers.go#L12-L23

which works and k8s starts killing the pod.

**Comment by JamieAP** [comment]
@povilasv That's only returning 404s on no checks and 500s on un-encodable JSON. There's a fix/spec change to be had there.

**Comment by martinroddam** [comment]
The current specification for go-operational states to return a 200 status code i.e. "I was able to perform the checks and here is your data". Perhaps it should not be used for the liveness probe, as you say.

Alerting on health checks can be a useful thing. It's just another tactic to complement metrics, not something to be depended upon or to substitute for them.

What if your app does something only periodically, like process batches of files as they appear, but overnight or at the weekend the permissions were changed on an S3 bucket you depend on. You'd want to know about that as soon as possible. A health check (assuming it is polled often) can tell you this. An alternative to this is some kind of synthetic monitoring, but since health checks often come out of the box for free, why not surface health data alongside your metrics? I'd quite like to see what health check was failing alongside a big spike in errors on my grafana dashboard.

Health checks are also designed to tell you whether or not your app can do what it needs to. If you rely on another API the health check tells you whether or not your app can hit it, not whether or not that API is up.

But leaving the whole idealogical debate about metrics and healthchecks aside for moment 😄 ...

This is just a little change to represent this data in a nicer way on a graph. I tried with counters and what the chart was representing felt better suited as a gauge.

**Comment by JamieAP** [comment]
> It's just another tactic to complement metrics, not something to be depended upon or to substitute for them.

It's fine saying that, but humans are humans and humans are lazy. It's best to prevent entirely the things you don't want to see if there isn't a compelling reason to risk it. I don't think there is here.

>What if your app does something only periodically

The health checks will fail and the pod will be killed if using ReadyUseHealthCheck (most/all of our apps are, and if we fix the non-200 return on health they all will). Our k8s state metrics (and associated alerts) will then detect the deployment is running less pods than desired and inform us. Your example scenario is already fully catered for by our existing setup. 

>I'd quite like to see what health check was failing alongside a big spike in errors on my grafana dashboard.

Like I said earlier, you'll almost never see any errors at the same time as failing health checks if you're configured properly. 1) for the reason I mentioned above, loose approximations and 2) if my app is registering errors, it's unlikely my health checks are failing because failing health checks imply unready pods. 

If I am registering errors I'm also logging them, looking at those is going to be far more insightful than a gauge going up or down by 1. 

>Health checks are also designed to tell you whether or not your app can do what it needs to.

They're primarily designed to do that.

>If you rely on another API the health check tells you whether or not your app can hit it, not whether or not that API is up.

Both my interpretations of this sentence are non-nonsensical. Either you're suggesting our APIs should monitor their own localhost (not very useful, things that depend on this API should monitor for that as it covers a wider range of failure cases). Or you're suggesting that "our app can hit API X" is not the same as "API X is up".

> But leaving the whole idealogical debate about metrics and healthchecks aside for moment smile ...
This is just a little change to represent this data in a nicer way on a graph. I tried with counters and what the chart was representing felt better suited as a gauge.

I appreciate you didn't introduce this but given we're here, I'd rather we use this PR to remove the instrumentation entirely than wave this change through on the basis this wasn't the conversation you wanted to have.

**Comment by martinroddam** [comment]
Can we do this in person next week - it's incredibly tedious over comments.

**Comment by JamieAP** [comment]
With the prohibitively large number of interested parties (this is the single most used repo in the organisation) any conclusion we reach together offline only risks someone equally as annoying as me disagreeing and the loop starts again.

**Comment by martinroddam** [comment]
So,

If we decide to change the behaviour of `/__/health` and return a 5xx in the event of any single check failure, it means that any health check failure could result in the app being killed and then crash-looping. Killing your app in the event of a 3rd party failure or failure to connect to another piece of infrastructure seems drastic to me.

I would have thought if you're not seeing any errors when your health check is down, then the health check is doing something redundant.

> If I am registering errors I'm also logging them, looking at those is going to be far more insightful than a gauge going up or down by 1.

I've found the health checks to be a quicker route to knowing the cause, but experiences will vary.

> failing health checks imply unready pods

Really? Health checks never fail after startup?

> Either you're suggesting our APIs should monitor their own localhost

Nope

> Or you're suggesting that "our app can hit API X" is not the same as "API X is up".

Yep. Sometimes when I can't watch Netflix the problem is with my router, not with Netflix.

Regarding this particular change - I was hoping this could go through so I could experiment with the outcome as one of only a handful of users. The wider discussion around whether or not people want health checks should be separate in my opinion.

**Comment by JamieAP** [comment]
>any health check failure could result in the app being killed and then crash-looping. 

Yup

>Killing your app in the event of a 3rd party failure or failure to connect to another piece of infrastructure seems drastic to me.

It's a trade off. We have no way to communicate "this is a failure you should reschedule the pod to another node for" and "this is not a failure you should...". The point of rescheduling elsewhere is to attempt to remedy issues not caused by the app (e.g. bad k8s node networking). 

>I would have thought if you're not seeing any errors when your health check is down, then the health check is doing something redundant.

Not in the case of your own example, where the app does real work infrequently but health checks constantly. 

>I've found the health checks to be a quicker route to knowing the cause, but experiences will vary.

I find that hard to believe. Given a metric "mongo-health" going up or down, sure that tells you which health check failed. It doesn't tell you why: bad networking, changed auth/perms, missing database? The logs will.

>Really? Health checks never fail after startup?

I think you've misunderstood? ReadyUseHealthChecks means a pod won't be marked active (have traffic routed to it, be scraped by prom) until the health checks pass. Also, and importantly, if the health checks stop passing (readiness is relevant always, not just at startup) the pod will revert to unready.

>Yep. Sometimes when I can't watch Netflix the problem is with my router, not with Netflix.

If I can reach an API, that implies I can both talk to it and it is up. If I can't talk to it, obviously that doesn't necessarily imply it's down. But it also doesn't matter which one it is, my app can't talk to it, I want to know about it. I'm not sure what we're disagreeing about in this case?

**Comment by mjgarton** [comment]
Disclaimer : I haven't caught up with everything in this thread yet.

@JamieAP to answer your question,  that behaviour was chosen so that consumers can rely on the health check behaving just like any other normal endpoint in the application.  If it manages to return the right response, it should return 200 and that shouldn't change to non-200 just because the content is different, so it's behaving as designed and as expected.  In short, it's not a special endpoint WRT response codes.

Conversely the ready endpoint uses a status code alone to indicate status, in order to match the historical approach of doing so for load balancers etc. Obviously this is a common approach which k8s has also adopted.

ReadyWhenHealthy just is a convenient way of getting both endpoints with these differing behaviours, but with the same underlying checking code. (which isn't always appropriate, but is often fine)

**Comment by JamieAP** [comment]
@mjgarton I think that comes with the drawback that our applications using /__/health for their liveness probe won't be terminated and rescheduled on another k8s node when they fail. Was that considered?

ReadyUseHealthCheck (i.e. the readiness probe) will remove the app from a service but it won't terminate the pod and give it a chance to reschedule elsewhere like the liveness probe will. As far as I'm aware the only way right now an app would be able to take advantage of that behaviour is to define another endpoint that does return non-200s on failed checks and use that.

**Comment by JamieAP** [comment]
Of course thinking about it, we could just point our liveness probes at the ready endpoint to achieve the same effect... Even if it is a little confusing wrt naming.

**Comment by mjgarton** [comment]
@JamieAP I probably didn't realise __health was being used for liveness.  I would using the  __ready endpoint for that, as you've already suggested.  That's exactly the kind of thing it was intended for, although I agree with you about the unfortunate naming situation.

If using __health for liveness is widespread, that suggests the naming is confusing enough to cause problems and we may want to reconsider names if we ever make a round of breaking changes for any reason. (or a v2)

**Comment by vnadgir** [comment]
From my initial PR -

> It would be great to be able to use healthchecks in order to do a few things
>
> -  In the case where the healthchecks check third party connectivity / synthetic checks the metrics will  be useful to paint a good picture of reliability of the third party service
>
> - In the case where the checks test connectivity with underlying datastores, the meters will help provide visibility of how reliable the datastores are

The idea was to have a one-stop shop where I could look at historical metrics from healthchecks for reliability information as well as look at current state like we do in `https://health.dev.uw.systems/`. Counters looked right for the former.

@JamieAP We do use the `/__/health` as a target for the `livenessProbe` endpoint to tide over intermittent/persistent failures at the moment in a lot of places. This is great for unattended reschedules. However, I am not convinced that `/__/health` should be used for checking liveness. But that is yet another discussion on the semantics of what the consumers of the endpoint should or should not do.

**Comment by vnadgir** [comment]
The primary intention with this metric was not about alerting , but to surface healthcheck information even when the app restarted and recovered due to `livenessProbe` looking at `/__/health` so that dependencies behaving "badly" can be looked proactively in needed. 

However I dont think we should overload liveness check with this endpoint.

**Comment by JamieAP** [comment]
@mjgarton It's relatively widespread:  
```
$ rg "/__/health" | wc -l
438
```

@vnadgir Liveness probes on /__/health currently do absolutely nothing but validate the endpoint exists due to the reasons mentioned above. 

What's your thoughts on an alternative target for liveness?

**Comment by vnadgir** [comment]
@JamieAP - As you suggest `ReadyUseHealthChecks` and thence `/__/ready` is a great proxy for the behaviour  I described.

**Comment by vnadgir** [comment]
@JamieAP - As you suggest `ReadyUseHealthChecks` and thence `/__/ready` is a good setup for achieving the behaviour I described. 

I think we need to separate out the app restarting from healthcheck failures. I dont have a ready-made answer for how we do it across the board. We should take that discussion up soon.

regarding the pattern of using health endpoint in livenessProbe,  
>$ rg "/__/health" | wc -l
> 438
I have used this before as a stop-gap when an app was creating a non-resilient DB connection at startup time. But that is not a great end state to be in. 

I just wonder if the discussion of metering healthchecks has moved off stage now as we debate  the semantics of `/__/health` endpoint and its related `/__/ready` endpoint.

**Comment by mjgarton** [comment]
@JamieAP I think an alternate target is well worth discussing - let's take it to an issue instead of this PR.

Returning to intent of the PR, and in light of discussion, but ignoring k8s liveness needs for now, what do people think?

I haven't much of an opinion either way on the choice of metric type used TBH, so I'm fine with this change.

I don't see a problem in general with metrics on the health endpoint.  I see it as an application endpoint, much like any other and people sometimes want metrics in relation to their application endpoints.

I'm not sure it should be in the core package, because it means a dependency on the prom library for everyone, but that's history and is not being changed in this PR.

Anyone other thoughts on this specific change? (Especially those who care about having metrics on a health endpoint)

**Comment by JamieAP** [comment]
I'm not convinced this instrumentation is a slam dunk no-brainer. I think the unified health check thing is of questionable value and introducing 400+ time series isn't free. That said I'm happy to be outvoted, disagree and commit.

**Comment by povilasv** [comment]
IMO, introducing metrics is ok in here, but we should agree on metric & label names as it PITA to change them later. 

People use prometheus for all sort of things like storing version info -> https://telecom-prometheus.prod.uw.systems/graph?g0.range_input=1h&g0.expr=etcd_server_version&g0.tab=1

and you can always drop the metrics before ingestion with relabel config, so there isn't really a problem.

Another thing I generally prefer having counters over gauges as counters have nice properties like the value persists across restarts (if you use `rate`), etc.

Maybe consider introducing error counter and success counter instead?

**Comment by martinroddam** [comment]
@povilasv Thanks for the comment. Not sure why I would need the value persisting across restarts. Especially for a health check. Error and success counters are kind of what was there before. What I want to see is a continuous horizontal line at value=1 to show my app is healthy, and a drop to 0 when it is not. Very easy to see.
Health checks are generally hit at a constant rate so I'm not really interested in seeing the rates of health check failures/successes over time.

**Comment by jakekeeys** [comment]
Also on the fence mostly because I don't fully understand the use case/value in the service this change intends to power.

**Pull request merged**
